version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn gcia.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 2
    volumes:
      - .:/app
      - ./static:/app/static  # Mount static files from the container to the host machine (optional)
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql  # Persist data to a named volume to retain DB data between restarts

volumes:
  mysqldata:  # Create a named volume for MySQL data persistence
