version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn gcia.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 2
    volumes:
      - ./GUARCIAN_CAPITAL_IA:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
