version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn gcia.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 2
    volumes:
      - .:/app
      - ./static:/app/static  # Mount static files from the container to the host machine (optional)
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-pghn3et!0o2m@*vzv)8b7i@jn7_=p=k17nd@y7!%mi-n58fyyz
      - DEBUG=False
      - DB_NAME=guardian_capital_db
      - DB_USER=gcia_admin
      - DB_PASSWORD=Tech@gcia1234
      - DB_HOST=db  # Use the db service name as the host
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: guardian_capital_db  # This should match DB_NAME in the web service
      POSTGRES_USER: gcia_admin         # This should match DB_USER in the web service
      POSTGRES_PASSWORD: Tech@gcia1234  # This should match DB_PASSWORD in the web service
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data to a named volume to retain DB data between restarts

volumes:
  pgdata:  # Create a named volume for PostgreSQL data persistence
